### ISSUE TITLE
Add config flags to disable the automatic propagation of the received broadcast messages

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/kadcast#57]
**Describe what you want implemented** 
The `PeerBuilder` should have a config flag to disable the automatic propagation of the received broadcast messages.
If this flag is `true` the `MessageHandler` shall not continue the propagation of a received `BroadcastMessage` 

In addition to this, the `Peer.broadcast` method should accept an optional kadcast height as a desired broadcast height.
If this is not specified, a full broadcast should be performed

**Describe "Why" this is needed**
In some use case, the propagation of the messages can be done only after a verification of the message content.
This verification is not performed by the kadcast library and it's completely delegated to the caller of the library.
Only after this validation succeded, a message should be broadcasted to the the remaining buckets.

The APIs should enable the client to act this way

**Describe alternatives you've considered**
~A clear and concise description of any alternative solutions or features you've considered.~

**Additional context**
~Add any other context or screenshots about the feature request here.~

**Comment by t00ts** [comment]
I suggest implementing this from the **enabling** [auto broadcast] point of view, as opposed to *disabling*. I find it much easier to understand when using bools.

For example:

`ENABLE_AUTO_BROADCAST = false` is pretty clear and self explanatory, whereas
`DISABLE_AUTO_BROADCAST = false` makes you think about what's actually going on

cc/ @herr-seppia
