### ISSUE TITLE
Allow to send messages to a specific target

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/kadcast#58]
**Describe what you want implemented** 
The Peer API should expose a `send` method to "broadcast" a message to a specific target.

**Describe "Why" this is needed**
This is required to handle a ping/pong paradigm useful in the following scenario
Eg:
* The client caller ask to broadcast a `FindBlock` message
* Receives multiple `BlockReady` responses
* Replies to only one of the previous responses with a `GetBlock` message
* The latter will send back a `Block` message

**Describe alternatives you've considered**
The client caller can broadcast a sort of "Ping" message to the network and handle the multiple response.

**Additional context**
~Add any other context or screenshots about the feature request here.~

**Comment by t00ts** [comment]
Does this function definition seem adequate? @herr-seppia 

```rust
    /// Send a message to a peer in the network.
    pub async fn send(&self, peer: PeerInfo, message: &[u8])
```

**Comment by herr-seppia** [comment]
> Does this function definition seem adequate?

Does the client know anything about `PeerInfo`?
Due to the fact this is a prerequisite for #59, maybe a `SocketAddr` is enough

What about this signature?

```rust
    /// Send a message to a peer in the network.
    pub async fn send(&self, message: &[u8], target: SocketAddr) {
```
